name: imageengine_helpers_dart
description: A Dart library for interacting with ImageEngine CDN, providing helper functions for image manipulation and URL generation.
version: 1.0.0
homepage: https://github.com/imgeng/imageengine-helpers-dart

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
